
# Loads default set of integrations. Do not remove.
default_config:

logger:
  default: info
  logs:
    custom_components.naim_muso: debug
    naimco: debug
    naimco.core: debug
    naimco.controller: debug